image:
  repository: ghcr.io/vanelin/k8s-controller
  tag: "0.1.2" # This is set by CI to the Git tag or commit SHA
  pullPolicy: IfNotPresent
# Node selector for multi-arch support
nodeSelector: {}
# kubernetes.io/arch: amd64
# kubernetes.io/arch: arm64

# Image pull secrets (if needed for private registry)
imagePullSecrets: []
# Application configuration
app:
  port: 8080
  logLevel: "info"
# Environment variables
env:
  KUBECONFIG: "~/.kube/config"
# Service configuration
service:
  type: ClusterIP
  port: 80
# Deployment configuration
deployment:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
