name: Smart cache cleanup - delete only after merge
on:
  pull_request:
    types: [closed]  # Only when PR is closed
  workflow_dispatch:
    inputs:
      cleanup_mode:
        description: 'Cleanup mode'
        required: true
        default: 'single'
        type: choice
        options:
          - single
          - all_branches
          - all_prs
          - everything
      branch:
        description: 'Branch name (for single branch cleanup)'
        required: false
        default: ''
      pr:
        description: 'PR number (for single PR cleanup)'
        required: false
        default: ''

jobs:
  prune:
    # Run only if PR was merged or manual dispatch
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout for branch info
        if: github.event_name == 'workflow_dispatch' && contains(github.event.inputs.cleanup_mode, 'all_branches')
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Smart cleanup based on event
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          CLEANUP_MODE: ${{ github.event.inputs.cleanup_mode }}
          BRANCH_INPUT: ${{ github.event.inputs.branch }}
          PR_INPUT: ${{ github.event.inputs.pr }}
        run: |
          set +e
          total_deleted=0
          
          # Function to delete caches for a ref
          delete_caches_for_ref() {
            local ref="$1"
            local ref_name="$2"
            echo "::group::Cleaning caches for $ref_name ($ref)"
            
            cache_ids=$(gh cache list --ref "$ref" --json id --jq '.[].id')
            
            if [ -z "$cache_ids" ]; then
              echo "No caches found for $ref"
            else
              ref_deleted=0
              echo "$cache_ids" | while read -r id; do
                if [ -n "$id" ]; then
                  echo "Deleting cache: $id"
                  if gh cache delete "$id"; then
                    ((ref_deleted++))
                  fi
                fi
              done
              
              actual_deleted=$(echo "$cache_ids" | wc -l)
              total_deleted=$((total_deleted + actual_deleted))
              echo "Deleted $actual_deleted caches for $ref_name"
            fi
            echo "::endgroup::"
          }
          
          # Handle different events and modes
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # PR was merged - clean both PR and source branch caches
            pr_number="${{ github.event.pull_request.number }}"
            source_branch="${{ github.event.pull_request.head.ref }}"
            target_branch="${{ github.event.pull_request.base.ref }}"
            
            echo "PR #$pr_number was merged from '$source_branch' to '$target_branch'"
            
            # Delete PR caches
            pr_ref="refs/pull/$pr_number/merge"
            delete_caches_for_ref "$pr_ref" "PR #$pr_number"
            
            # Delete source branch caches (only if merged to main)
            if [[ "$target_branch" == "main" ]]; then
              branch_ref="refs/heads/$source_branch"
              delete_caches_for_ref "$branch_ref" "branch '$source_branch'"
              
              echo "::notice::Cleaned caches for merged PR #$pr_number and source branch '$source_branch'"
            else
              echo "::notice::Cleaned caches for PR #$pr_number (merged to '$target_branch', not main)"
            fi
            
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            case "$CLEANUP_MODE" in
              "single")
                if [[ -n "$PR_INPUT" ]]; then
                  ref="refs/pull/$PR_INPUT/merge"
                  delete_caches_for_ref "$ref" "PR #$PR_INPUT"
                elif [[ -n "$BRANCH_INPUT" ]]; then
                  ref="refs/heads/$BRANCH_INPUT"
                  delete_caches_for_ref "$ref" "branch '$BRANCH_INPUT'"
                else
                  echo "Please specify a branch or PR number for single cleanup"
                  exit 1
                fi
                ;;
                
              "all_branches")
                echo "Cleaning ALL branch caches except main"
                
                # Get all remote branch refs except main
                all_branches=$(git for-each-ref --format='%(refname:short)' refs/remotes/origin/ | grep -v 'origin/main' | sed 's|origin/||')
                
                if [ -z "$all_branches" ]; then
                  echo "No feature branches found"
                else
                  echo "Found branches to clean:"
                  echo "$all_branches"
                  
                  for branch in $all_branches; do
                    ref="refs/heads/$branch"
                    delete_caches_for_ref "$ref" "branch '$branch'"
                  done
                fi
                ;;
                
              "all_prs")
                echo "Cleaning ALL PR caches"
                
                # Get all PR cache refs
                pr_refs=$(gh cache list --limit 500 --json ref --jq '.[] | select(.ref | startswith("refs/pull/")) | .ref' | sort -u)
                
                if [ -z "$pr_refs" ]; then
                  echo "No PR caches found"
                else
                  echo "Found PR refs to clean:"
                  echo "$pr_refs"
                  
                  echo "$pr_refs" | while read -r ref; do
                    if [ -n "$ref" ]; then
                      pr_num=$(echo "$ref" | sed 's|refs/pull/\([0-9]*\)/.*|\1|')
                      delete_caches_for_ref "$ref" "PR #$pr_num"
                    fi
                  done
                fi
                ;;
                
              "everything")
                echo "Cleaning ALL caches except main branch caches"
                
                # Get all cache refs except main
                all_refs=$(gh cache list --limit 1000 --json ref --jq '.[] | select(.ref != "refs/heads/main") | .ref' | sort -u)
                
                if [ -z "$all_refs" ]; then
                  echo "No non-main caches found"
                else
                  echo "Found refs to clean:"
                  echo "$all_refs"
                  
                  echo "$all_refs" | while read -r ref; do
                    if [ -n "$ref" ]; then
                      if [[ "$ref" == refs/pull/* ]]; then
                        pr_num=$(echo "$ref" | sed 's|refs/pull/\([0-9]*\)/.*|\1|')
                        delete_caches_for_ref "$ref" "PR #$pr_num"
                      elif [[ "$ref" == refs/heads/* ]]; then
                        branch=$(echo "$ref" | sed 's|refs/heads/||')
                        delete_caches_for_ref "$ref" "branch '$branch'"
                      else
                        delete_caches_for_ref "$ref" "ref '$ref'"
                      fi
                    fi
                  done
                fi
                ;;
            esac
          fi
          
          echo "Smart cache cleanup completed"
          echo "Total estimated caches deleted: $total_deleted"