name: Cleanup Untagged Images

on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:

jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: ${{ github.repository_owner }}
          name: k8s-controller
          token: ${{ secrets.PAT }}
          untagged-keep-latest: 2