name: Cleanup Feature Branch Images

on:
  schedule:
    - cron: "0 1 * * SUN"
  workflow_dispatch:

jobs:
  delete-feature-images:
    name: Delete Feature Branch Images
    runs-on: ubuntu-latest
    steps:
      - name: Delete images with short SHA in tag
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: vanelin
          name: k8s-controller
          token: ${{ secrets.PAT }}
          tag: '.*-[0-9a-f]{7,8}$'