name: Cleanup Untagged Images

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: k8s-controller
          package-type: container
          delete-only-untagged-versions: true
          min-versions-to-keep: 2
          token: ${{ secrets.PAT }}