name: Cleanup Feature Branch Images

on:
  schedule:
    - cron: "0 2 * * SAT"
  workflow_dispatch:

jobs:
  delete-feature-images:
    name: Delete Feature Branch Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete feature branch images with git hashes
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: k8s-controller
          package-type: container
          token: ${{ secrets.PAT }}
          min-versions-to-keep: 20
          ignore-versions: '^(latest|(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(@sha256:.*)?)$'